### ISSUE TITLE
chrome动画显示不自然

### ISSUE THREAD

**Issue by laizhiwei123** [linuxdeepin/deepin-kwin#17]
chrome在deepin15.10下最大化和还原的时候显示很不自然。还有就是在开启自动调节色温后，鼠标不动会隐藏。
版本：deepin15.10新装的
硬件:magicbook R5 版

**Comment by zccrs** [comment]
有没有试过原生的kde环境？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
