### ISSUE TITLE
Kwin下很多软件顶部栏显示延迟1秒左右，而且很肥大

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/deepin-kwin#31]
我的系统：deepin15.10.1 所有软件最新  窗口管理器 KWin
拿terminator这款软件来说，我说的顶部栏值得是  widon@widon-PC所在的那个栏  
这个顶部栏会延迟1秒显示，而且太粗壮，deepin在美化在做了很多好的改进，但这个顶部栏是败笔，需要优化  
![肥大，而且延迟1秒显示](https://user-images.githubusercontent.com/12093211/59109130-13ea2d00-896f-11e9-9e3d-c15b7c6627ea.png)

**Comment by BLumia** [comment]
重复： https://github.com/linuxdeepin/developer-center/issues/1210

ps. 看到你在不同 repo 提了很多 issue ，Deepin 目前主要关注的 Issue 都集中在 Developer Center 处理，可以考虑直接在那里提。
