### ISSUE TITLE
The cursor is placed at the edge of the window, and the icon that changes the size of the window is not displayed.

### ISSUE THREAD

**Issue by fanhengyuan** [linuxdeepin/deepin-kwin#34]
I found this problem. I don't know if it is a bug.

As shown in the following GIF diagram, the right deepin terminal is normal.

Non-deepin official software such as teamview, VirtualBox cursors are placed on the edge, and no icon for changing the window is displayed.

But you can change the window size.

![pic](https://tva1.sinaimg.cn/large/006Xmmmggy1g5rifogeobg31hc0t04qq.gif)

Do not display the icon for the red box below.

![avatar](https://tva1.sinaimg.cn/large/006Xmmmggy1g5tgrjxfvdj309j0demxx.jpg)

Forum link here:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=181702

**Comment by BLumia** [comment]
Please track this issue at https://github.com/linuxdeepin/developer-center/issues/1497 :)
