### ISSUE TITLE
Enourmous lag after suspend to ram

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-kwin#36]
after opening my laptop (suspend to ram) I notice a huge lag on input and framerate.
In my editor the cursor moves with a clear lag and a small javascript game shows the slow and irregular framerate. 
Noticed this first after change to deepin-kwin.
It is even hard to type this, as the characters appear a bit later after the key press...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
