### ISSUE TITLE
No dock, no window borders, no resizing, no moving, settings appear just once

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-kwin#37]
Hey, the last update was a huge win again.
I restarted because I wanted to change the scaling...
Now I have no dock anymore, the windows that open are not resizeable of course and not moveable as well. 
I can open the settings, but once closed I have to restart to be able to open them again - for one time.

DDE was so nice once and now it turns more and more to a not usable Desktop. I need my Laptop for work and it too often is updated to a not usable state.
Please try changes before releasing them...

Using Linux Arch with DDE...

**Comment by felixonmars** [comment]
Do you still have deepin-kwin 0.1.0-2 installed? It was broken with latest KDE update. An updated 0.1.0-3 package has been uploaded to fix it.

**Comment by DasJott** [comment]
Yup, just saw there is an update. Sorry for the rant. I was on an urgent project and suddenly it stopped working...

Thank you for the update!
