### ISSUE TITLE
Shortcut Alt ^ is not working anymore

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-kwin#40]
One thing I loved about deepin-wm was the shortcut for switching between instnaces of _one_ application.
With kwin that shortcut is dead. I saw it was not set anymore after the change, but even after resetting it to that key shortcut ALT - ^ it does not work.

Please fix!

**Comment by BLumia** [comment]
Hi and the shortcut for walk through windows of current application is <kbd>Alt + ~</kbd>, if you have KDE's `systemsettings5` package installed, you can also tweak this setting in `Workspace > Window Management > Task Switcher > Shortcuts > Current application` :)

**Comment by DasJott** [comment]
I set it in deepin settings but it doesn't work. Do I really need to install systemsettings5?

**Comment by BLumia** [comment]
I don't have a clean environment to test out, maybe the current released dde-control-center have some issue with the dde-kwin integration? The v20 control center I can tested works fine here so you wont need to install the kde systemsettings package :)

**Comment by DasJott** [comment]
As I just switched back to deepin-wm the shortcut works just fine. 
It must have something to do with kwin...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
