### ISSUE TITLE
Choose window from dock is buggy

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-kwin#41]
Multiple instances of VSCode opened.  
Move to the according symbol on dock.  
On hovering two mini previews appear.  

   _Fine so far!_  

**1st bug:**
- If you hover on one of the mini previews, every window except the chosen one is transparent.  _Okay!_  
- Even both the mini previews getting transparent.  
_Not that okay..._  
- If you click on one of the mini previews, it closes and the chosen window is opaque, but all of the other windows keep transparent. Even new opened ones are!!  
_Totaly **not** okay!_

So you end up with an unusable desktop system.  
The only possibility to make it usable again is to again hover over that symbol in dock, then hover over the mini previews, then just move back over the dock back to the desktop.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
