### ISSUE TITLE
manjaro+kde+deepin后使用kwin导致wine程序从最小化恢复窗口卡住

### ISSUE THREAD

**Issue by woqulegenicheng** [linuxdeepin/deepin-kwin#43]
在不安装deepin-kwin时kde可以正常最小化wine程序窗口，但是在使用deepin-kwin后，deepin桌面和kde桌面在最小化wine程序后，再次从任务栏开启后，窗口会卡死，无法操作，包括使用deepin-wine

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
