### ISSUE TITLE
Arch KDE update break deepin-kwin

### ISSUE THREAD

**Issue by hbarsaiyan** [linuxdeepin/deepin-kwin#45]
**Steps to Reproduce:**
Install kde 5.75.0-1 updates

**Describe the bug:**
Window effects in DDE stop working.

**Comment by felixonmars** [comment]
It's a known issue for now. Please see https://github.com/linuxdeepin/developer-center/issues/1945 for some advices.

**Comment by hbarsaiyan** [comment]
> It's a known issue for now. Please see [linuxdeepin/developer-center#1945](https://github.com/linuxdeepin/developer-center/issues/1945) for some advices.

Thanks for the quick reply. I have downgraded the plasma dependencies of deepin to 5.74.0 so it's working fine for now.
