### ISSUE TITLE
Crashes when enabling windows effects; No transparency

### ISSUE THREAD

**Issue by kreon28** [linuxdeepin/deepin-kwin#47]
**Distro & Version**

Arch Linux with Deepin desktop environment 2:2021.1.25-1
kernel 5.10.16-zen1-1-zen
nvidia driver nvidia-dkms 460.39-1

Running 
pacman -S deepin deepin-extra

as a standard install i.a.: deepin-wm and deepin-kwin altogether

deepin-wm: 1.9.38-5
deepin-kwin: 5.2.0.13-1

**The result - bugs:**
a. No transparency 
b. Kwin errors in journald
c. Changing wallpapers and screensaver makes desktop crash

**Details:**
Option One:
1. exit DDE
a. Remove deepin-wm and deepin-anything-arch
b. Install deepin-anything-dkms; reinstall deepin-kwin and deepin-dock
c. (optionally) delete:  ~/USER/.config/kwinrc
2. launch DDE
- The wallpaper and screensaver option works. 
- No transparency.
- Default windows effects are working
- In control center:  windows effects button is visible, but turning it on crashes kwin, so button returns to off option;
   no option for transparency
- After above kwin crash -  windows effects stop working

Option Two:
1. exit DDE
a. Remove deepin-kwin
b. Reinstall deepin-wm
2. launch DDE
- The wallpaper and screensaver option crashes to desktop
- In control center: no button for windows effects nor transparency
- windows effects work
- transparency is present only for dock (some default preset) 

**Expected behavior:**
- Having transparency option slider
- Working transparency 
- Working windows effects
- Working wallpapers and screensaver option

Bugs are similar to issue:
https://github.com/linuxdeepin/developer-center/issues/1555

**Comment by felixonmars** [comment]
deepin-kwin is broken again with kwin 5.21.

**Comment by kreon28** [comment]
> [arch.log](https://github.com/linuxdeepin/deepin-kwin/files/6029274/arch.log)
> deepin-kwin is broken again with kwin 5.21.

Ok, but I'm on 5.20 version and it is still malfunctioning.

**Comment by kreon28** [comment]
Right now in arch groups : deepin and deepin-extra there is no deepin-kwin as a standard installation (only deepin-wm)
After upgrade of deepin group in arch (deepin-wm to 1.9.38-6) and manually installation of add-on deepin-kwin (5.3.4-1), issues which were described above are gone.
Also, there is no need to use deepin-anything-dkms anymore, updated versions of deepin-anything (5.07-2) and deepin-anything-arch (5.0.7-27) do the thing.
